spring.application.name=plantillas

# Usamos variables con valores por defecto para URL y User
spring.datasource.url=${DB_URL:jdbc:mysql://mysql-32865d12-equipo.a.aivencloud.com:28250/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${DB_USER:avnadmin}

# Aquí está el truco: No le pongas valor por defecto aquí para que GitHub no detecte nada
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true